apiVersion: v2
name: video-msg
description: A Helm chart for screen recording with audio commentary tool with backend and frontend
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Screen Recording Team
keywords:
  - video-msg
  - video
  - recording
  - java
  - spring-boot
  - vue
