apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-msg.fullname" . }}-config
  labels:
    {{- include "video-msg.labels" . | nindent 4 }}
data:
  database.host: {{ include "video-msg.database.host" . | quote }}
  database.port: {{ include "video-msg.database.port" . | quote }}
  database.name: {{ include "video-msg.database.name" . | quote }}
