---
spring:
  application:
    name: "vmsg"
  datasource:
    url: "jdbc:mariadb://localhost:3306/video-message"
    username: "video-message"
    password: "video-message"
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MariaDBDialect"
        format_sql: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
file-storage:
  base-directory: "./video-storage"
server:
  port: 8080
  servlet:
    context-path: "/api"
