---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: video-msg-database-secret
  namespace: default
spec:
  encryptedData:
    database.password: AgAy/WGItBNw6U9luUP+ToT/iGfbSe2bkBalVkcfL21ZLH40Ftzmeki71g/L4hniiqVyKHWVCdPi+qzH0KSQ+g6vTCJnGCawE77regjCXmoWIc9onF+f2XnF0uv6wujUwVrARhY1OdHHje6o/Nj0E9MOL2SfOaxGiqkFPPO9ur8EZwujKobHeswemqM2Yj83zXl8LA7XAPc2VmP+QTccsjCRFIDU2NM8jnAFmlny+U5ltTBDn01PuNtx38LEjZLT6nw3b+wQmG3VbkfiuX72TwhA+D7emsvlbvAC5cUvdbeI/EGiPxTJXPbt6cpsWk171OP9wqO0kqbHuE3wYt09wLwTbDNQiL96AF4YykPlFKrpon1B03ZXxesr0wJSDlRDJ4WUkKFA+9sjpX/jKUd4lmm4FcOtJETcTnZR9HyGKroNyjKIlyBF2eet3tyYMbJDsXn4Y4mlzO69uVBzLMmqQMvlaATSVEfrIhP8uWBHb0uqS4+mOr1r9hZRN8mZO6uU53Jt9YTfjP0SnDxry4N7rTHct6qnA0wi6qZu/9HoonoWGL7hinnTHpnnjPc7lL0B6mVwCxaaScIxe1B7NXgsZbJixH2Iu94ymSM/wL0D5vQ0U087/POwSNDilYydiUX/5Amn3J+/8g6vGrNHLUR9vw+CME5SCPT37DgQSq1NRezBaGBBzYhkfQsy8phZV6kd/ChAHP8/jjb3ViLkdMgdQLNL5HGCfWaA/P3BevLL1VqdJ7ieEzkiX5oB8rRQFLdmjctwBGVWvybG
    database.user: AgAfHLHtQCEn00BiKeaTDYU8r0LiHnG4y+K4seQ+eyC+HUCjdG4RBUjDOqShW6b1hUbVvSXerHMqokxthdNvGPPW0vK8dPh7YH7Wt+of0Lhpm+9p4WH3NrcbwDiHhlXrVGOZ3VFUGf21EYl8q5cKR9nX0FQwzFxNhZGvpQanAimFJ6cRiiCMAkGJqFZvwfDn0VKSA1Bv7bE73vQG+L2qQ3eY134/TNCjApOWpjRgGc3+YpAKvGb1Tim5RF8/7qrnPxTd53gM1d0M8AV6kK0hDrQr/0UUKYvStA15hbUaS4vQCjthaaYvXWTWltIAxH3JR8K5SYxck5uY5b3jr+gFXQFLlaLLjIdK0rlbNfgbXD99SVF6RiZ0jIndiij4eE3VE0gh/P1ZGZKthWI7kIl6nfKGC15rlfcedCbdnyLaZDo0VWZcBNMzoFGgr/WhQG/wikYxuFftVqzedas44fMpmWEsBX5z2uS9SG5bPEyPuhZVuLxOlYLSwV7I6vAT43y9C0qAYarRur0cWcRI1u0QbVb3oD97KbQta6jOgN8oG+Hq0PShVfZIkm/pRMAtS4eWqunf4CUfz1xaMKm5U8VcOKpjUmns/rmBmG2fUAKBqHszqXcfrQ8YalGMYfjEf/8o5fU/zUvJ74S5X9D3UeZPJMu2Ik/xlWosB1QSe/pTM+zZe7Y9HTwt4neDlWvmC2YYZGxjkQML3QXN3fcL5Mlr
  template:
    metadata:
      name: video-msg-database-secret
      namespace: default
    type: Opaque
